// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_necessary_sacrifice = "CgkImLeVnfkcEAIQCg"; // <GPGSID>
        public const string achievement_oneway_ticket = "CgkImLeVnfkcEAIQBw"; // <GPGSID>
        public const string achievement_instant_fugue = "CgkImLeVnfkcEAIQBQ"; // <GPGSID>
        public const string achievement_too_easy = "CgkImLeVnfkcEAIQCA"; // <GPGSID>
        public const string achievement_professional_occultist = "CgkImLeVnfkcEAIQDQ"; // <GPGSID>
        public const string achievement_demonic_bishop = "CgkImLeVnfkcEAIQCw"; // <GPGSID>
        public const string achievement_clang = "CgkImLeVnfkcEAIQDg"; // <GPGSID>
        public const string achievement_appetizing = "CgkImLeVnfkcEAIQCQ"; // <GPGSID>
        public const string achievement_demonic_ordination = "CgkImLeVnfkcEAIQAg"; // <GPGSID>
        public const string achievement_in_the_name_of_the_lord = "CgkImLeVnfkcEAIQDw"; // <GPGSID>
        public const string achievement_junior = "CgkImLeVnfkcEAIQBg"; // <GPGSID>
        public const string achievement_satanist_baptism = "CgkImLeVnfkcEAIQAQ"; // <GPGSID>
        public const string achievement_first_step = "CgkImLeVnfkcEAIQBA"; // <GPGSID>
        public const string achievement_infernal_confirmation = "CgkImLeVnfkcEAIQAw"; // <GPGSID>
        public const string achievement_occult_addict = "CgkImLeVnfkcEAIQDA"; // <GPGSID>

}

